language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
services:
  - redis-server
before_install:
  - export PIP_USE_MIRRORS=true
matrix:
    fast_finish: true
    include:
      - python: "3.5"
        env: DJANGO=2.2
install:
  - pip install tox tox-venv tox-travis
script:
  - tox
env:
  - DJANGO=2.2
  - DJANGO=3.0
